Support passing of va_list
Trilliant/SLF4EC pull request #4
Opened 2018-11-30 00:37 UTC by zr5dt

To use SLF4EC with some libraries that have their own logging API, support for passing an explicit va_list instead of an implied variable list (using ...) is needed. This commit adds a new function (_logv) to allow for just that.

2019-11-19 22:26 UTC, jeremfg requested changes
Hi Dario,

I know it's really late, but I'm looking to integrate your PR officially.
If you prefer I take over, I'm happy to. Lemme know how you want to proceed. In either case you will be credited for this.

2019-11-19 22:26 UTC, jeremfg commented on src/slf4ec.c
> +                if (categories[i]) {
Is there any benefit for this change?
There's no guarantee the user passed a zeroed-out array on initialization, especially if out-of-bounds. So it doesn't protect against much imho.

2019-11-19 22:26 UTC, jeremfg commented on src/slf4ec.c
> +    return _privateLog(NULL, NULL, NULL, category, &level, formatStr, vaList);
My understanding is that you should call va_copy() and va_end() between each function calls, as the whole reason why va_copy() exists is to support implementations where va_list contains an offset to the stack pointer, which changes between each function call.

Might be simpler to pass a pointer to va_list instead.

2019-11-19 22:26 UTC, jeremfg commented on src/slf4ec.c
> +    return _privateLog(file, &Line, function, category, &level, formatStr, vaList);
Same comment about needing a va_copy() here, or change for a pointer to va_list

2019-11-19 22:26 UTC, jeremfg commented on src/slf4ec.c
> +    va_copy(ap, vaList);
Missing a corresponding call to va_end() in this function

2019-11-20 16:59 UTC, zr5dt commented
Hi Jeremie,

Yes, please go ahead and modify as you see fit.

Regards
Dario

> On Nov 19, 2019, at 2:26 PM, Jérémie Faucher-Goulet <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
> @jeremfg requested changes on this pull request.
> 
> Hi Dario,
> 
> I know it's really late, but I'm looking to integrate your PR officially.
> If you prefer I take over, I'm happy to. Lemme know how you want to proceed. In either case you will be credited for this.
> 
> In src/slf4ec.c <https://github.com/Trilliant/SLF4EC/pull/4#discussion_r348198784>:
> 
> > @@ -130,7 +130,9 @@ LogResult setLevels(const uint8_t level)
>              uint_fast8_t i;
>              for (i = 0; i < nbCategories; i++)
>              {
> -                categories[i]->currentLogLevel = level;
> +                if (categories[i]) {
> Is there any benefit for this change?
> There's no guarantee the user passed a zeroed-out array on initialization, especially if out-of-bounds. So it doesn't protect against much imho.
> 
> In src/slf4ec.c <https://github.com/Trilliant/SLF4EC/pull/4#discussion_r348199858>:
> 
> >  }
>  
>  LogResult nfLog1(const LogCategory* const category, const uint8_t level, const char* const formatStr, ...)
>  {
> -    // SONAR has some weird troubles handling the HANDLE_LOG macro.
> -    HANDLE_LOG1(NULL, NULL, NULL);
> +    LogResult returnCode;
> +    va_list vaList;
> +    va_start(vaList, formatStr);
> +    returnCode = _privateLog(NULL, NULL, NULL, category, &level, formatStr, vaList);
> +    va_end(vaList);
> +    return returnCode;
> +}
> +
> +LogResult nfLogv(const LogCategory* category, const uint8_t level, const char* formatStr, va_list vaList)
> +{
> +    return _privateLog(NULL, NULL, NULL, category, &level, formatStr, vaList);
> My understanding is that you should call va_copy() and va_end() between each function calls, as the whole reason why va_copy() exists is to support implementations where va_list contains an offset to the stack pointer, which changes between each function call.
> 
> Might be simpler to pass a pointer to va_list instead.
> 
> In src/slf4ec.c <https://github.com/Trilliant/SLF4EC/pull/4#discussion_r348201007>:
> 
> > +    va_list vaList;
> +    va_start(vaList, formatStr);
> +    returnCode = _privateLog(file, &Line, function, category, &level, formatStr, vaList);
> +    va_end(vaList);
> +    return returnCode;
> +}
> +
> +LogResult yfLogv(const char* const file,
> +                 const uint32_t line,
> +                 const char* const function,
> +                 const LogCategory* const category,
> +                 const uint8_t level,
> +                 const char* const formatStr,
> +                 va_list vaList)
> +{
> +    return _privateLog(file, &Line, function, category, &level, formatStr, vaList);
> Same comment about needing a va_copy() here, or change for a pointer to va_list
> 
> In src/slf4ec.c <https://github.com/Trilliant/SLF4EC/pull/4#discussion_r348201169>:
> 
> >  {
> -    const uint64_t timestamp = logTimeApi();
> +    va_list ap;
> +    va_copy(ap, vaList);
> Missing a corresponding call to va_end() in this function
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/Trilliant/SLF4EC/pull/4?email_source=notifications&email_token=ACFXQH66BT7YTH2YAMUDZ6TQURRYFA5CNFSM4GHLEZIKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCMEYV4A#pullrequestreview-319392496>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ACFXQH2SJLE3KPZS6LW62PDQURRYFANCNFSM4GHLEZIA>.
>

2019-11-20 21:22 UTC, merged